config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to:  'homes#top'
  get "/home/about" => "homes#about", as: "about"
  get "search" => "searches#search"#検索機能
  get "search_result" => "searches#search_result"


  resources :users, only:[:show, :index, :edit, :update] do
    resource :relationships, only:[:create, :destroy]#フォロー
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :books, only:[:new, :create, :show, :index, :edit, :update, :destroy] do
    resources :comments, only:[:create, :destroy]#コメント
    resource :favorites, only:[:create, :destroy]#いいね
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

	has_one_attached :image
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body , length:{ maximum: 200 }, presence: true

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  #----------------------↓検索機能（book）--------------------------------
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
  #------------------------------------------------------------------------

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: []
  before_action :test_edit, only:[:upadte, :edit, :destroy]

  def create
    @book= Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]= "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books= Book.all
      @user= current_user
      render :index
    end
  end

  def index
    @book= Book.new
    @books= Book.all
    @user= current_user
  end

  def show
    @book= Book.new#新規作成
    @book_show= Book.find(params[:id])#アソシ
    @user= @book_show.user#個別ユーザー情報
    @book_comment= Book.find(params[:id])#コメント
    @comment= Comment.new#コメント

  end

  def edit
    @book= Book.find(params[:id])
  end

  def update
    @book= Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]= "You have created book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book= Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def test_edit
    @book= Book.find(params[:id])
    if(@book.user != current_user)
      redirect_to books_path
    end
  end



end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
  <h1>User info</h1>

  <%= image_tag user.get_profile_image(100,100) %>

    <table>
    	<tbody>
    		<tr>
    		  <th>name</th>
    		  <th><%=  user.name %></th>
    		</tr>
    		<tr>
    		  <th>introduction</th>
    		  <th><%=  user.introduction %></th>
    		</tr>
    		<tr>
    		<th>follows</th>
          <th><%= link_to user.followings.count, user_followings_path(user) %></th>
        </tr>
        <tr>
          <th>followers</th>
          <th><%= link_to user.followers.count, user_followers_path(user) %></th>
        </tr>
    	</tbody>
    </table>


    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
    <% end %>


    <h1>New book</h1>
    <%= form_with model: book do |f| %>

  	<h4>Title</h4>
      <%= f.text_field :title %>
    <h4>Opinion</h4>
      <%= f.text_area :body %>
      <%= f.submit 'Create Book', class: 'btn btn-success' %>

    <% end %>

app/views/books/edit.html.erb
  <div class="container">

  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h2>Editing Book</h2>

        <diV id="error_explanation">
          <% if @book.errors.any? %>
          <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </diV>


        <%= form_with model: @book, method: :patch do |f| %>

          <label for="inputTitle">Title</label>
          <div>
              <%= f.text_field :title, autofocus: true, id:"inputTitle" %>
          </div>

          <label for="inputOpinion">Opinion</label>
          <div>
            <%= f.text_field :body, autofocus: true, id:"inputOpinion" %>
          </div>

          <%= f.submit "Update Book", class: 'btn btn-success'%>
        <% end %>

        <%= link_to "Show", book_path(@book.id) %>
        <%= " |" %>
        <%= link_to "Back", '/books' %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<html>


    <div class="container">

        <% if @book.errors.any? %>
          <%= @book.errors.count %>error prohibited this obj from being saved:
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
        <% end %>

      <div class="row">
          <div class="col-md-3">
            <!-----------------------部分テンプレ------------------------------------>
            <%= render 'list', user: @user, book: @book %>

          </div>

          <div class="col-md-8 offset-md-1">

          <%= render 'searches/search' %>

            <h1>Books</h1>
            <table>
                <thead>
                	<th></th>
                    <th>Title</th>
                    <th>Opinion</th>
                    <th colspan="3"></th>
                </thead>

                <tbody>
                    <% @books.each do |book| %>
                        <tr>
                        	<td>
                      	    <%= link_to user_path(book.user) do %>
                                  <%= image_tag book.user.get_profile_image(100,100) %>
                              <% end %>
                          </td>

                          <td><%= link_to book.title, book_path(book), method: :get %>
                            <span><%= book.body %></span>
                          </td>

                          <td>
                             <% if book.favorited_by?(current_user) %>

                                  <%= link_to book_favorites_path(book), method: :delete do %>
                                    <i class="fa-solid fa-heart">  <%= book.favorites.count %></i>
                                  <% end %><!--押下後-->


                                <% else %>

                                  <%= link_to book_favorites_path(book), method: :post do %>
                                    <i class="fa-regular fa-heart">  <%= book.favorites.count %></i>
                                  <% end %><!--押下前-->

                              <% end %>
                          </td>

                          <td><%= book.comments.count %>コメント</td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
          </div>
      </div>
    </div>
</html>

app/views/books/new.html.erb
<h1>New Book</h1>
  <%= form_with model: @book do |f| %>

  	<h4>Title</h4>
      <%= f.text_field :title %>
    <h4>Opinion</h4>
      <%= f.text_area :body %>
    <%= f.submit 'Create Book' %>

  <% end %>

app/views/books/show.html.erb
<div class="container">

      <% if @book.errors.any? %>
        <%= @book.errors.count %>error prohibited this obj from being saved:
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
      <% end %>

  <div><%= flash[:notice] %></div>
  <div class="row">
    <div class="col-md-3">
          <!-----------------------部分テンプレ------------------------------------>
            <%= render 'list', user: @user, book: @book %>
    </div>


    <div class="col-md-8 offset-md-1">

        <h1>Book detail</h1>
        <table>
            <thead>
            	<th></th>
                <th></th>
                <th></th>
                <th colspan="3"></th>
            </thead>

            <tbody>
                <tr>
                    <td>
                        <%= link_to user_path(@book_show.user) do %>
                          <%= image_tag @book_show.get_image, class:"card-img-top"; %>
                          <%=  @book_show.user.name %>
                        <% end %>
                    </td>
                    <td><%= link_to @book_show.title, book_path(@book_show), method: :get %></td>
                    <td><%= @book_show.body %></td>

                    <td>
                        <% if @book_show.favorited_by?(current_user) %>

                                  <%= link_to book_favorites_path(@book_show), method: :delete do %>
                                    <i class="fa-solid fa-heart">  <%= @book_show.favorites.count %></i>
                                  <% end %><!--押下後-->


                                <% else %>

                                  <%= link_to book_favorites_path(@book_show), method: :post do %>
                                    <i class="fa-regular fa-heart">  <%= @book_show.favorites.count %></i>
                                  <% end %><!--押下前-->

                        <% end %>
                    </td>

                    <td>
                        <% if @book_show.user == current_user %>
                            <%= link_to "Edit", edit_book_path(@book_show), class: "btn btn-success" %>
                            <%= link_to "Destroy", book_path, class: "btn btn-danger", method: :delete, "data-confirm" => "本当に消しますか？" %>
                        <% end %>
                    </td>

                </tr>
            </tbody>
        </table>
<!---------------------------------------------↓コメント-------------------------------------------------------------------->
        <h2 class="comment-count"><%= @book_show.comments.count %>コメント</h2>

        <%= form_with model:[@book_comment, @comment] do |f| %>
            <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", class: "w-100" %>
            <%= f.submit "送信する" %>
        <% end %>

        <table>
            <thead>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th colspan="4"></th>
            </thead>

            <tbody>

                    <% @book_comment.comments.each do |comment| %>
                        <tr>
                            <td><%= link_to user_path(comment.user) do %>
                                <%= image_tag comment.user.get_profile_image(100,100) %>
                            <% end %>
                            </td>
                            <td><%= comment.user.name %></td>
                            <td><%= comment.created_at.strftime('%Y/%m/%d') %></td>
                            <td><%= comment.comment %></td>
                            <td>
                                <% if comment.user == current_user %>
                                <div class="comment-delete">
                                  <%= link_to "削除", book_comment_path(comment.book, comment), method: :delete %>
                                </div>
                                <% end %>
                            </td>
                        </tr>
                    <% end %>
            <tbody>
        </table>
    </div>

  </div>
</div>